# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-01 05:08
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import paintstore.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('body', models.TextField(default='', max_length=1200)),
                ('publish_start_date', models.DateField(default=datetime.datetime.now, verbose_name='Date to start publishing')),
                ('publish_end_date', models.DateField(default=datetime.datetime(2019, 7, 1, 0, 0), verbose_name='Date to end publishing')),
                ('link', models.CharField(blank=True, default='', max_length=400)),
                ('hidden', models.BooleanField(default=False)),
                ('under_review', models.BooleanField(default=True)),
                ('contact', models.CharField(blank=True, default='', max_length=200)),
                ('approver', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcement_approver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BuildingFundCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('amount', models.DecimalField(decimal_places=2, default='0', max_digits=10)),
                ('notes', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BuildingFundYearGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=80, null=True)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('amount', models.DecimalField(decimal_places=2, default='0', max_digits=10)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BuildingFundYearPledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=80, null=True)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('amount', models.DecimalField(decimal_places=2, default='0', max_digits=10)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(max_length=1200)),
                ('color', paintstore.fields.ColorPickerField(max_length=7)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=400, null=True)),
                ('date_start', models.DateField(default=datetime.datetime.now)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('track_rsvp', models.BooleanField(default=False)),
                ('display_override', models.CharField(blank=True, choices=[('default', 'Default: Displays 14 days in advance'), ('hide', 'Hide Event'), ('show', 'Show Event')], default='default', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtendedGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
                ('group_type', models.IntegerField(choices=[(0, 'Community Group'), (1, 'Management'), (2, 'Committee')])),
                ('notes', models.TextField(blank=True, max_length=300, null=True)),
                ('date_formed', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('date_dissolved', models.DateField(blank=True, null=True)),
                ('meeting_day', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday'), (7, 'Irregular')], help_text='Day of the week the group regularly meets if any', null=True)),
                ('meeting_time', models.TimeField(blank=True, help_text='Meeting time of the the group in 24hr format ie. 13:00 for 1pm', null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            bases=('auth.group',),
        ),
        migrations.CreateModel(
            name='GroupAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('attendance', models.IntegerField(choices=[(0, 'Present'), (1, 'Absent'), (2, 'Excused'), (3, 'Unknown')])),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newswire.ExtendedGroup')),
            ],
        ),
        migrations.CreateModel(
            name='OrderOfService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('text', models.TextField(blank=True, default='')),
                ('service_name', models.CharField(choices=[('sunday-morning-english', 'Sunday Morning - English Service')], default='sunday-morning-english', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=80, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=80, null=True, verbose_name='Last Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('prefered_name', models.CharField(blank=True, help_text='We will use this name around the site instead of a combination of last+first name.', max_length=120, null=True, verbose_name='Preferred Name')),
                ('maiden_name', models.CharField(blank=True, max_length=80, null=True, verbose_name='Maiden Name')),
                ('gender', models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], max_length=1, null=True, verbose_name='Gender')),
                ('date_record_updated', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_marriage', models.DateField(blank=True, null=True)),
                ('date_of_baptism', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('home_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address_block', models.CharField(blank=True, max_length=12, null=True)),
                ('address_street', models.CharField(blank=True, max_length=140, null=True)),
                ('address_unit', models.CharField(blank=True, max_length=12, null=True)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=12, null=True)),
                ('is_regular', models.BooleanField(default=True)),
                ('is_member', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('MO', 'Mother'), ('FA', 'Father'), ('BRO', 'Brother'), ('SIS', 'Sister'), ('SON', 'Son'), ('DAUG', 'Daughter'), ('GRMA', 'Grand Mother'), ('GRFA', 'Grand Father'), ('GRSON', 'Grand Son'), ('GRDAUG', 'Grand Daughter')], max_length=10)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_relationship', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_relationship', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rsvp', models.CharField(choices=[('notgoing', 'Not Going'), ('interested', 'Interested'), ('going', 'Going')], default='notgoing', max_length=30)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newswire.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SundayAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('english_congregation', models.PositiveSmallIntegerField(default=0)),
                ('chinese_congregation', models.PositiveSmallIntegerField(default=0)),
                ('childrens_church', models.PositiveSmallIntegerField(default=0)),
                ('preschoolers', models.PositiveSmallIntegerField(default=0)),
                ('nursery', models.PositiveSmallIntegerField(default=0)),
                ('under_review', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, max_length=300, null=True)),
                ('approver', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sunday_attendance_approver', to=settings.AUTH_USER_MODEL)),
                ('submitter', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sunday_attendance_submitter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyVerse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2019, 7, 1, 0, 0))),
                ('verse', models.TextField(default='', max_length=1200)),
                ('reference', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='groupattendance',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newswire.Profile'),
        ),
        migrations.AddField(
            model_name='extendedgroup',
            name='leader',
            field=models.ManyToManyField(blank=True, related_name='leader_profile', to='newswire.Profile'),
        ),
        migrations.AddField(
            model_name='extendedgroup',
            name='member',
            field=models.ManyToManyField(blank=True, related_name='leader_member', to='newswire.Profile'),
        ),
        migrations.AddField(
            model_name='buildingfundcollection',
            name='building_fund_year_goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newswire.BuildingFundYearGoal'),
        ),
        migrations.AddField(
            model_name='buildingfundcollection',
            name='building_fund_year_pledge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newswire.BuildingFundYearPledge'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='newswire.Category', verbose_name='Audience'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='submitter',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcement_submitter', to=settings.AUTH_USER_MODEL),
        ),
    ]
